In [31]:
import pandas as pd
import pyarrow.parquet as pq
from tqdm import tqdm
import seaborn as sns
import matplotlib.pyplot as plt
import torch
import torch.nn as nn

from CustomConvolution import CustomConvolution
from Resnet import resnet34
from Icecube_Dataloader import ICECUBE_Dataset, collate_fn

In [5]:
model = resnet34(pretrained = False)
model.fc = nn.Sequential(nn.ReLU(),nn.Linear(in_features=512, out_features=2)) # Changed FC layer for our task
model.load_state_dict(torch.load("./model.pth", weights_only=True))
model.eval()

ResNet(
  (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
  (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (relu): ReLU(inplace=True)
  (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
  (layer1): Sequential(
    (0): BasicBlock(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
    (1): BasicBlock(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
  

In [6]:
pqfile = '/home/washindeiru/primaryDrive/iceCube/icecube-neutrinos-in-deep-ice/train_meta.parquet'
path_batch = '/home/washindeiru/primaryDrive/iceCube/icecube-neutrinos-in-deep-ice/train_2/'

batch_num=1 # There are 660 batches total, and the batch number should be iterated in range(660).
lr = 1e-06
num_epochs = 1
batch_size = 8

In [7]:
from torch.utils.data import DataLoader

ice_dataset = ICECUBE_Dataset(pqfile,path_batch,batch_num)
train_dataset = ice_dataset
train_dataloader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True,collate_fn=collate_fn, num_workers=11)

In [8]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

model = model.to(device)

## Testy resnet34

In [22]:
data_iter = iter(train_dataloader)

In [23]:
first_batch = next(data_iter)
print(f"input tensor shape: {first_batch['input_tensor'].shape}")
print(f"label shape: {first_batch['label'].shape}")
input_tensor = first_batch['input_tensor']
label = first_batch['label']

result = model(input_tensor.to(device))

input tensor shape: torch.Size([8, 3, 1, 1353])
label shape: torch.Size([8, 2])


In [24]:
print(label)
print(result)

tensor([[3.6048, 1.8711],
        [2.2220, 0.6766],
        [1.0161, 1.8798],
        [3.7294, 2.4844],
        [2.0646, 1.8477],
        [5.1723, 1.0635],
        [4.9785, 2.0359],
        [5.8960, 1.6530]])
tensor([[1.8678, 0.4480],
        [1.8951, 0.4782],
        [1.8502, 0.4527],
        [1.9987, 0.6189],
        [1.8686, 0.5201],
        [1.8639, 0.4552],
        [2.2402, 0.6513],
        [1.9037, 0.4603]], device='cuda:0', grad_fn=<AddmmBackward0>)


In [25]:
first_batch = next(data_iter)
print(f"input tensor shape: {first_batch['input_tensor'].shape}")
print(f"label shape: {first_batch['label'].shape}")
input_tensor = first_batch['input_tensor']
label = first_batch['label']

result = model(input_tensor.to(device))

input tensor shape: torch.Size([8, 3, 1, 413])
label shape: torch.Size([8, 2])


In [26]:
print(label)
print(result)

tensor([[5.7039, 2.2642],
        [3.4613, 1.0516],
        [5.8169, 1.2964],
        [2.7429, 1.7953],
        [4.5754, 1.5763],
        [4.4149, 0.9783],
        [3.9197, 0.8383],
        [5.3693, 1.6063]])
tensor([[1.9876, 0.7728],
        [2.0006, 0.7075],
        [2.0056, 0.7648],
        [2.0030, 0.7887],
        [2.0672, 0.9412],
        [1.9224, 0.8326],
        [1.9729, 0.7341],
        [1.8973, 0.7303]], device='cuda:0', grad_fn=<AddmmBackward0>)


In [27]:
first_batch = next(data_iter)
print(f"input tensor shape: {first_batch['input_tensor'].shape}")
print(f"label shape: {first_batch['label'].shape}")
input_tensor = first_batch['input_tensor']
label = first_batch['label']

result = model(input_tensor.to(device))

input tensor shape: torch.Size([8, 3, 1, 99])
label shape: torch.Size([8, 2])


In [28]:
print(label)
print(result)

tensor([[0.0953, 2.2676],
        [4.9200, 0.7379],
        [1.9765, 2.3542],
        [5.6664, 1.2383],
        [4.7591, 1.6117],
        [0.9421, 0.5935],
        [5.3007, 0.3330],
        [2.4062, 2.0654]])
tensor([[2.5535, 1.5434],
        [2.3566, 1.2632],
        [2.3686, 1.2451],
        [2.5433, 1.2922],
        [2.6899, 1.3942],
        [2.9595, 1.5677],
        [2.2108, 1.1504],
        [2.4975, 1.3824]], device='cuda:0', grad_fn=<AddmmBackward0>)


In [29]:
first_batch = next(data_iter)
print(f"input tensor shape: {first_batch['input_tensor'].shape}")
print(f"label shape: {first_batch['label'].shape}")
input_tensor = first_batch['input_tensor']
label = first_batch['label']

result = model(input_tensor.to(device))

input tensor shape: torch.Size([8, 3, 1, 125])
label shape: torch.Size([8, 2])


In [30]:
print(label)
print(result)

tensor([[1.4001, 0.9430],
        [2.1231, 0.7901],
        [1.6267, 2.9878],
        [0.8161, 1.8120],
        [2.0868, 1.2569],
        [2.1439, 2.0720],
        [3.1082, 1.7864],
        [0.7499, 1.7321]])
tensor([[3.0108, 1.2168],
        [2.4539, 1.1640],
        [2.8013, 0.6397],
        [2.4335, 1.2146],
        [2.6550, 1.4389],
        [2.4673, 1.2137],
        [2.1148, 1.0480],
        [2.4935, 1.1982]], device='cuda:0', grad_fn=<AddmmBackward0>)
